# fly.toml app configuration file generated for nest-js-boilerplate on 2025-10-17T19:20:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nest-js-boilerplate'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024