# fly.toml app configuration file generated for nest-js-boilerplate on 2025-07-31T08:50:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nest-js-boilerplate'
primary_region = 'iad'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1